#define CANT_LETRAS 5
#define CANT_INTENTOS 6
#define ACIERTO_TOTAL 100
#define ACIERTO_PARCIAL 50
#define PARTIDAS_MAX 8
#define PREMIO_MAYOR 10000
#define PREMIO_MENOR 2000
#define DESCUENTO_INTENTO 500

